repos:
# -   repo: local
#     hooks:
#     -   id: isort
#         name: isort
#         stages: [commit, push]
#         language: system
#         entry: isort
#         args: 
#         -   "--length-sort"
#         -   "--profile"
#         -   "black"
#         -   "--line-length=120"
#         -   "--skip"
#         -   "whisper"
#         -   "."
#         always_run: true
#         pass_filenames: false

-   repo: local
    hooks:
    -   id: black
        name: black
        stages: [commit, push]
        language: system
        entry: black
        args: 
        -   "--line-length=120"
        -   "."
        always_run: true
        pass_filenames: false

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        stages: [commit, push]
        language: system
        entry: mypy
        args: 
        -   "--config-file=.github/mypy/mypy.ini"
        -   "condense/"
        -   "tests/"
        always_run: true
        pass_filenames: false

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        stages: [commit, push]
        language: system
        entry: pytest
        args: 
        -   "tests/"
        always_run: true
        pass_filenames: false

# TODO: Add eslint to the pre-commit hooks
# -   repo: local
#     hooks:
#     -   id: client
#         name: client
#         stages: [commit, push]
#         language: system
#         entry: npx
#         args: 
#         -   "eslint"
#         -   "./client"
#         always_run: true
#         pass_filenames: false

# -   repo: local
#     hooks:
#     -   id: server
#         name: server
#         stages: [commit, push]
#         language: system
#         entry: npx
#         args: 
#         -   "eslint"
#         -   "./server"
#         always_run: true
#         pass_filenames: false

-   repo: local
    hooks:
    -   id: client
        name: client
        stages: [commit, push]
        language: system
        entry: bash
        args: 
        -   "-c"
        -   "cd ./client && npm run test"
        always_run: true
        pass_filenames: false

-   repo: local
    hooks:
    -   id: server
        name: server
        stages: [commit, push]
        language: system
        entry: bash
        args: 
        -   "-c"
        -   "cd ./server && npm run test"
        always_run: true
        pass_filenames: false