name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# save workspaces to speed up testing
env:
  CONDENSE_SAVE_WORKSPACE: "True"

jobs:
  code_style:
    runs-on: ubuntu-20.04
    # Pin action version by commit hash to maximize trust, ref: https://securitylab.github.com/research/github-actions-building-blocks/
    steps:
    - name: Checkout Condense
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: Set up Python 3.9
      uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -e .[dev]
    - name: Lint with isort
      run: isort --profile black --length-sort --line-width 120 -c .
    - name: Lint with black
      run: black -l 120 --check .
    - name: Check types with mypy
      run: mypy --config-file .github/mypy/mypy.ini condense/ tests/

    timeout-minutes: 10